### ISSUE TITLE
Create Heroku integration

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-extensions#17]
In order for us to more effectively leverage our SaltStack infrastructure it would be useful to have an extension that allows us to interface with Heroku. This should include the ability to:

- [x] Read, set, and unset environment variables
- [ ] List, control, and scale processes
- [ ] Provision and scale addons

**Comment by shaidar** [comment]
[PR#30](https://github.com/mitodl/salt-extensions/pull/30) merged
