### ISSUE TITLE
Update ElasticSearch returner

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-extensions#3]
The current state of the elasticsearch returner doesn't fully work with Elasticsearch v2.x. It needs to be updated, as well as updating the naming scheme for the indexes in order to make them simpler to reason about and search across in the Kibana UI.

**Comment by shaidar** [comment]
This has been updated, but there's still minor bug with nested keys that have a dot in the name.

**Comment by blarghmatey** [comment]
We have abandoned the idea of using the elasticsearch server as our target for salt return data and will focus on using the pgjson returner instead.
