### ISSUE TITLE
Write saltpack renderer

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-extensions#7]
In order to overcome some of the pain of using GPG for encrypting data in YAML files I would like to add support for SaltPack as a renderer. This will allow for more easily extracting secrets data into Jinja files to import into pillar YAML. This is because SaltPack is not whitespace sensitive, whereas GPG is. Because of this, trying to substitute GPG data into the YAML from the Jinja file is painful.

**Comment by shaidar** [comment]
Moving gpg pillar data to vault, so not working on this anymore.
